<?php

namespace Telanflow\Sms\Test;

use Illuminate\Foundation\Application;
use Orchestra\Testbench\TestCase;

class SmsTest extends TestCase
{
    use SmsTestTrait;

    /**
     * @param Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return ['Telanflow\Sms\ServiceProvider'];
    }

    /**
     * @param Application $app
     *
     * @return array
     */
    protected function getPackageAliases($app)
    {
        return [
            'Sms' => "Telanflow\Sms\Facade",
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('sms', require __DIR__.'/../config/config.php');

        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);
    }

    protected function loadMigrationsFrom($app)
    {
        $this->artisan('migrate', ['--database' => 'testbench']);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->loadMigrationsFrom(__DIR__.'/database');
    }
}
